version: '3.6'

services:
  db:
    image: "${DOCKER_HUB_PROXY}postgres:11.6"
    command:
      -c fsync=${FSYNC:-off}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  base:
    image: "${IMAGE_BASE}bds/overhave-base:${POETRY_CONTENT_HASH:-unset}"
    build:
      context: .
      dockerfile: docker/Dockerfile.base
      network: host
      args:
        DOCKER_HUB_PROXY: "${DOCKER_HUB_PROXY}"